"""
BharatVerse - Recommendations API
Exposes explainable recommendations generated by the solver
"""

from typing import List
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from ..database.connection import get_db
from ..database.db_models import RecommendationModel
from ..schemas.schemas import RecommendationResponse

router = APIRouter(prefix="/api/recommendations", tags=["Recommendations"])

@router.get("", response_model=List[RecommendationResponse])
def get_recommendations(status: str = None, db: Session = Depends(get_db)):
    query = db.query(RecommendationModel)
    if status:
        query = query.filter(RecommendationModel.status == status)
    return query.order_by(RecommendationModel.created_at.desc()).all()

@router.get("/{rec_id}", response_model=RecommendationResponse)
def get_recommendation_by_id(rec_id: str, db: Session = Depends(get_db)):
    rec = db.query(RecommendationModel).filter(RecommendationModel.rec_id == rec_id).first()
    if not rec:
        raise HTTPException(status_code=404, detail="Recommendation not found")
    return rec
